name: 10 - 8 - Controlling the Execution Flow

on: workflow_dispatch

#Job-level continue-on-error

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  tests:
    runs-on: ubuntu-latest
    needs: build
    continue-on-error: true
    steps:
      - run: exit 1 # Simulate test failure

  deploy:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - run: echo "🚀 Deploying!"
