name: 11 - Working with Inputs

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: Skip deployment and only print build output
        type: boolean
        default: false
      target:
        description: Which environment the workflow will target
        type: environment
        required: true
      tag:
        description: Release from which to build and deploy
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from tag ${{ inputs.tag }}"
  deploy:
    runs-on: ubuntu-latest
    if: ${{ !inputs.dry-run }}
    environment: ${{ inputs.target }}
    needs: build
    steps:
      - name: Deploy
        run: echo "Deploying to ${{ inputs.target }}"
