name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS

on:
  workflow_dispatch: # Manually triggered

jobs:
  dependency-update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check for dependency updates
        uses: ./.github/actions/js-dependency-update
