name: 18 - 3 - Reusable Workflows

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: ./.github/workflows/18-1-reusable-workflows.yml
    with:
      target-directory: dummmy-dir
  e2e-tests:
    uses: y2hhbmr1/github-actions-course-example-e2e/.github/workflows/e2e.yml@main
    needs: deploy
    secrets: inherit
